*********************************************************************
* Copyright 2005 Automated Software Tools Corporation               *
* Copyright 2013 Cat Herder Software, LLC                           *
* Copyright 2018 Joachim Bartz, Germany                             *
*                                                                   *
* This source code is part of z390 assembler/emulator package.      *
*                                                                   *
* The z390 package is distributed under GNU general public license  *
*                                                                   *
* Author - Don Higgins                                              *
*********************************************************************
* 2006-04-30  DSH Initial version                                   *
*********************************************************************

         MACRO
         TESTSYN2 &P1
         WTO      'WTO FROM TESTSYN2 WITH P1=&P1'
         MEND
